/*
 * File: app/view/dashboard/ResponsiveBlock.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.dashboard.ResponsiveBlock', {
    extend: 'Ext.container.Container',
    alias: 'widget.dashboardresponsiveblock',

    requires: [
        'Ext.container.Container'
    ],

    height: 250,
    layout: 'anchor',

    items: [
        {
            xtype: 'container',
            cls: 'left_part',
            items: [
                {
                    xtype: 'container',
                    layout: 'fit'
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'right_part',
            items: [
                {
                    xtype: 'container',
                    layout: 'fit'
                }
            ]
        }
    ]

});