/*
 * File: app/view/pages/BlankPageContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.pages.BlankPageContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.pagesblankpagecontainer',

    requires: [
        'SenchaDash.view.pages.BlankPageContainerViewModel',
        'Ext.container.Container'
    ],

    viewModel: {
        type: 'pagesblankpagecontainer'
    },
    layout: 'anchor',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            cls: 'blank-page-container',
            html: '<div class=\'fa-outer-class\'><span class=\'fa fa-clock-o\'></span></div><h1>Coming Soon!</h1><span class=\'blank-page-text\'>Stay tuned for updates</span>',
            width: '100%'
        }
    ],
    listeners: {
        render: 'onContainerRender'
    },

    onContainerRender: function(component, eOpts) {
                var vsize=Ext.getBody().getViewSize();
                component.setHeight(vsize.height - 100);
    }

});