/*
 * File: app/view/pages/Error500Window.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.pages.Error500Window', {
    extend: 'Ext.window.Window',
    alias: 'widget.pageserror500window',

    requires: [
        'SenchaDash.view.pages.Error500WindowViewModel',
        'SenchaDash.view.pages.Error500WindowViewController',
        'Ext.container.Container',
        'Ext.toolbar.Spacer',
        'Ext.form.Label',
        'Ext.button.Button'
    ],

    controller: 'pageserror500window',
    viewModel: {
        type: 'pageserror500window'
    },
    autoShow: true,
    cls: 'error-page-container',
    closable: false,
    title: 'Sencha',
    titleAlign: 'center',
    maximized: true,
    modal: true,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'container',
            height: 400,
            minHeight: 400,
            minWidth: 400,
            width: 500,
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'tbspacer',
                    // flex: 0.5
                },
                {
                    xtype: 'label',
                    // flex: 2,
                    cls: 'error-page-top-text',
                    // padding: 10,
                    // style: {
                    //     'font-size': '40px;',
                    //     'text-align': 'center;'
                    // },
                    text: '500'
                },
                {
                    xtype: 'label',
                    // flex: 0.6,
                    autoShow: true,
                    cls: 'error-page-describe-text',
                    text: 'Woh!'
                },
                {
                    xtype: 'label',
                    cls: 'error-page-bottom-text',
                    text: 'Something went wrong and server couldn\'t process your request.'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            cls: 'error-page-bottom-text',
                            text: 'Try going back to our'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            cls: 'error-page-button',
                            text: 'home page',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'tbspacer',
                    flex: 1
                }
            ]
        }
    ]

});