/*
 * File: app/view/pages/Login.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.pages.Login', {
    extend: 'Ext.window.Window',
    alias: 'widget.pageslogin',

    requires: [
        'SenchaDash.view.pages.LoginViewModel',
        'SenchaDash.view.pages.LoginViewController',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.form.trigger.Trigger',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    controller: 'pageslogin',
    viewModel: {
        type: 'pageslogin'
    },
    autoShow: true,
    cls: 'signin-page-top-container page-with-background',
    closable: false,
    title: 'Sencha',
    titleAlign: 'center',
    maximized: true,
    modal: true,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'container',
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'form',
                    width: 455,
                    padding:20,
                    cls:'login-form-wrap',
                    header: false,
                    manageHeight: false,
                    layout: {
                        type: 'vbox',
                    },
                    items: [
                        {
                            xtype: 'container',
                            cls: 'lock-screen-body',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    cls: 'lock-screen-top-label',
                                    width: 415,
                                    text: 'Sign in your account'
                                },
                                {
                                    xtype: 'textfield',
                                    cls: 'signin-textbox',
                                    height: 55,
                                    margin: '10 0',
                                    width: 415,
                                    fieldLabel: 'Username',
                                    hideLabel: true,
                                    emptyText: 'example@example.com',
                                    triggers: {
                                        mytrigger1: {
                                            cls: 'signin-email-trigger'
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    cls: 'signin-textbox',
                                    height: 55,
                                    margin: '10 0',
                                    width: 415,
                                    fieldLabel: 'Username',
                                    hideLabel: true,
                                    emptyText: 'Password',
                                    inputType:'password',
                                    triggers: {
                                        mytrigger1: {
                                            cls: 'signin-password-trigger'
                                        }
                                    }
                                },
                                {
                                    xtype: 'container',
                                    padding: '5 0 10 0',
                                    width: 415,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            margin:'0 0 0 1',
                                            cls: 'form-panel-font-color rememberMeCheckbox',
                                            height: 30,
                                            boxLabel: 'Remember me'
                                        },
                                        {
                                            xtype: 'container',
                                            html: '<div class=\'forgot-pass-text\'>Forgot Password ?</div>',
                                            height:30
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    cls: 'lock-screen-login-button',
                                    height: 55,
                                    width: 415,
                                    iconAlign: 'right',
                                    iconCls: 'fa  fa-angle-right',
                                    text: 'Login',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    html: '<div class="outer-div"><div class="new-user-text">OR</div></div>',
                                    width: 415,
                                    margin:'10 0'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'signin-facebook-button',
                                    height: 55,
                                    width: 415,
                                    iconAlign: 'right',
                                    iconCls: 'fa  fa-facebook',
                                    text: 'Login with Facebook',
                                    listeners: {
                                        click: 'onButtonClick1'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    html: '<div class="outer-div"><div class="new-user-text">New User</div></div>',
                                    width: 415,
                                    margin:'10 0'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'signin-create-account-button',
                                    height: 55,
                                    width: 415,
                                    iconAlign: 'right',
                                    iconCls: 'fa  fa-user-plus',
                                    text: 'Create Account',
                                    listeners: {
                                        click: 'onButtonClick11'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});