/*
 * File: app/view/pages/LoginViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.pages.LoginViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.pageslogin',

    onButtonClick: function(button, e, eOpts) {
        // this.getView().destroy();
        window.location.hash = "dashboard.MainContainer";

    },

    onButtonClick1: function(button, e, eOpts) {
        // this.getView().destroy();
        window.location.hash = "dashboard.MainContainer";
    },

    onButtonClick11: function(button, e, eOpts) {
        // var registerPage = Ext.create('SenchaDash.view.pages.Register');
        // var viewPort=this.getView().up().up().query('#mainCardPanel')[0];
        // this.getView().destroy();
        // viewPort.add(registerPage);
        window.location.hash = "pages.Register";
    }

});
