/*
 * File: app/view/pages/ProfileContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.pages.ProfileContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.pagesprofilecontainer',

    requires: [
        'SenchaDash.view.pages.ProfileContainerViewModel',
        'Ext.plugin.Responsive',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.button.Segmented',
        'Ext.button.Button',
        'Ext.panel.Panel',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'pagesprofilecontainer'
    },

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            responsiveConfig: {
                'width <= 800': {
                    hidden: true
                },
                'width > 800': {
                    hidden: false
                }
            },
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 200,
                            width: '100%',
                            title: 'John Doe'
                        },
                        {
                            xtype: 'label',
                            text: 'John Doe'
                        },
                        {
                            xtype: 'label',
                            text: 'Sr. Manager'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'segmentedbutton',
                            items: [
                                {
                                    text: 'F'
                                },
                                {
                                    text: 'T'
                                },
                                {
                                    text: 'G+'
                                },
                                {
                                    text: 'Hot'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Follow'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            text: 'San Jose ,CA'
                        },
                        {
                            xtype: 'label',
                            text: 'Member Since 1 Year'
                        },
                        {
                            xtype: 'label',
                            text: 'http://someWebsite.com'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'About Me',
                    items: [
                        {
                            xtype: 'label',
                            text: 'Lorem Ipsum'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'label',
                            flex: 1,
                            text: '450 Likes'
                        },
                        {
                            xtype: 'label',
                            flex: 1,
                            text: '7,000  Freinds'
                        }
                    ]
                }
            ],
            plugins: [
                {
                    ptype: 'responsive'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 6,
            autoScroll: true,
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            emptyText: 'What are you thinking?'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Video',
                                                    tooltip: {
                                                        text: 'Add Video'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Aud',
                                                    tooltip: {
                                                        text: 'Add Audio'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Files',
                                                    tooltip: {
                                                        text: 'Upload Files'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Share'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 100,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            height: 30,
                                                            width: '100%'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'User A'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'From Mobile  -20 Minutes Ago'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Lorem Ipsum.Meassage From Some User'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Up'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Down'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Comment'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 100,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            height: 30,
                                                            width: '100%'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'User A'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'From Mobile  -20 Minutes Ago'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Lorem Ipsum.Meassage From Some User'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Up'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Down'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Comment'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 100,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            height: 30,
                                                            width: '100%'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'User A'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'From Mobile  -20 Minutes Ago'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Lorem Ipsum.Meassage From Some User'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Up'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Down'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Comment'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 100,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            height: 30,
                                                            width: '100%'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'User A'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'From Mobile  -20 Minutes Ago'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Lorem Ipsum.Meassage From Some User'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Up'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Down'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Comment'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 100,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            height: 30,
                                                            width: '100%'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'User A'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'From Mobile  -20 Minutes Ago'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Lorem Ipsum.Meassage From Some User'
                                                        },
                                                        {
                                                            xtype: 'image',
                                                            height: 100
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Up'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Down'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Comment'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    width: 100,
                                                    items: [
                                                        {
                                                            xtype: 'image',
                                                            height: 30,
                                                            width: '100%'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'User A'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            flex: 1,
                                                            text: 'From Mobile  -20 Minutes Ago'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Lorem Ipsum.Meassage From Some User'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Up'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            glyph: 72,
                                                            text: 'Down'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            text: 'Comment'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Now'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    flex: 1,
                                                                    title: 'SomeOne Shared An Image',
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 201,
                                                                            width: 201,
                                                                            src: 'resources/images/friends/f2.png'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    flex: 1,
                                                                    title: 'Job Meeting',
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'stretch'
                                                                    }
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    flex: 1,
                                                                    title: 'SomeOne Did Something',
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'label',
                                                                            flex: 1,
                                                                            text: 'Some Said This Thing. I cant remember'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    flex: 1,
                                                                    layout: {
                                                                        type: 'hbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 100,
                                                                            width: 100,
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: 'Some Said This Thing. I cant remember'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'label',
                                                            text: 'Yesterday'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    flex: 1,
                                                                    title: 'SomeOne Shared An Image',
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 201,
                                                                            width: 201,
                                                                            src: 'resources/images/friends/f2.png'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    flex: 1,
                                                                    title: 'Job Meeting',
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'label',
                                                                            flex: 1,
                                                                            text: 'Lorem Ipsum'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'panel',
                                                                    flex: 1,
                                                                    title: 'SomeOne Did Something',
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'label',
                                                                            flex: 1,
                                                                            text: 'Some Said This Thing. I cant remember'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'stretch'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    width: 100,
                                                                    layout: {
                                                                        type: 'vbox',
                                                                        align: 'center'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 80,
                                                                            width: '100%',
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: '30 Min Ago'
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    flex: 1,
                                                                    layout: {
                                                                        type: 'hbox',
                                                                        align: 'stretch'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'image',
                                                                            height: 100,
                                                                            width: 100,
                                                                            src: 'resources/images/friends/f2.png'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            text: 'Some Said This Thing. I cant remember'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});