/*
 * File: app/view/charts/GaugeAndRadialPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.charts.GaugeAndRadialPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.chartsgaugeandradialpanel',

    requires: [
        'SenchaDash.view.charts.GaugeAndRadialPanelViewModel',
        'Ext.chart.PolarChart',
        'Ext.chart.series.Gauge',
        'Ext.chart.series.sprite.PieSlice',
        'Ext.chart.axis.Numeric',
        'Ext.chart.axis.Category',
        'Ext.chart.series.Radar',
        'Ext.chart.interactions.Rotate'
    ],

    viewModel: {
        type: 'chartsgaugeandradialpanel'
    },
    title: 'Gauge and Radial Charts',

    items: [
        {
            xtype: 'container',
            cls: 'responsive-cell-container',
            height: 250,
            items: [
                {
                    xtype: 'panel',
                    height: 250,
                    layout: 'fit',
                    headerPosition: 'bottom',
                    title: 'Gauge Chart',
                    items: [
                        {
                            xtype: 'polar',
                            colors: [
                                '#115fa6',
                                '#94ae0a',
                                '#a61120',
                                '#ff8809',
                                '#ffd13e',
                                '#a61187',
                                '#24ad9a',
                                '#7c7474',
                                '#a66111'
                            ],
                            bind: {
                                store: '{gaugechartstore}'
                            },
                            series: [
                                {
                                    type: 'gauge',
                                    field: 'position',
                                    needle: true
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-cell-container',
            height: 250,
            items: [
                {
                    xtype: 'panel',
                    height: 250,
                    layout: 'fit',
                    headerPosition: 'bottom',
                    title: 'Radial Chart',
                    items: [
                        {
                            xtype: 'polar',
                            colors: [
                                '#115fa6',
                                '#94ae0a',
                                '#a61120',
                                '#ff8809',
                                '#ffd13e',
                                '#a61187',
                                '#24ad9a',
                                '#7c7474',
                                '#a66111'
                            ],
                            bind: {
                                store: '{radialchartstore}'
                            },
                            axes: [
                                {
                                    type: 'numeric',
                                    fields: [
                                        'yvalue'
                                    ],
                                    grid: true,
                                    position: 'radial'
                                },
                                {
                                    type: 'category',
                                    fields: [
                                        'xvalue'
                                    ],
                                    grid: true,
                                    position: 'angular'
                                }
                            ],
                            series: [
                                {
                                    type: 'radar',
                                    xField: 'xvalue',
                                    yField: 'yvalue'
                                },
                                {
                                    type: 'radar',
                                    xField: 'x',
                                    yField: 'y2'
                                }
                            ],
                            interactions: [
                                {
                                    type: 'rotate'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});