/*
 * File: app/view/charts/LineAndAreaPanelViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.charts.LineAndAreaPanelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.chartslineandareapanel',

    requires: [
        'Ext.data.Store'
    ],

    stores: {
        marketshareoneentitystore: {
            model: 'SenchaDash.model.DataXYModel',
            data: [
                {
                    xvalue: 2011,
                    yvalue: 946.5
                },
                {
                    xvalue: 2012,
                    yvalue: 584.03
                },
                {
                    xvalue: 2013,
                    yvalue: 559.24
                },
                {
                    xvalue: 2014,
                    yvalue: 306.2
                }
            ]
        },
        yearwisemarketsharestore: {
            model: 'SenchaDash.model.MultiDataXYModel',
            data: [
                {
                    xvalue: 2011,
                    y1value: 517.27,
                    y2value: 520.3,
                    y3value: 291.41,
                    y4value: 420.24
                },
                {
                    xvalue: 2012,
                    y1value: 389.38,
                    y2value: 632.31,
                    y3value: 982.98,
                    y4value: 771.08
                },
                {
                    xvalue: 2013,
                    y1value: 287.24,
                    y2value: 440.78,
                    y3value: 549.99,
                    y4value: 627.71
                },
                {
                    xvalue: 2014,
                    y1value: 505.25,
                    y2value: 631.07,
                    y3value: 570.43,
                    y4value: 583.67
                }
            ]
        }
    }

});