/*
 * File: app/view/charts/MainContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.charts.MainContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.chartsmaincontainer',

    requires: [
        'SenchaDash.view.charts.MainContainerViewModel',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.interactions.PanZoom',
        'Ext.chart.PolarChart',
        'Ext.chart.series.Pie',
        'Ext.chart.series.sprite.PieSlice',
        'Ext.chart.series.Pie3D',
        'Ext.chart.interactions.RotatePie3D',
        'Ext.chart.series.Gauge',
        'Ext.chart.series.Radar',
        'Ext.chart.series.Line'
    ],

    viewModel: {
        type: 'chartsmaincontainer'
    },
    cls: 'coditas-charts-container',

    items: [
    {
        xtype: 'container',
        cls: 'responsive-page-row',
        layout: 'anchor',
        items: [
            {
                xtype: 'container',
                cls: 'left-part',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'quick-graph-panel',
                                height: 300,
                                ui: 'light', 
                                margin:10,   
                                layout: 'fit',
                                headerPosition: 'bottom',
                                iconCls: 'fa fa-area-chart',
                                manageHeight: false,
                                title: 'Area Chart',
                                bodyPadding:15,
                                items: [
                                    {
                                        xtype: 'cartesian',
                                        colors: [
                                            '#115fa6',
                                            '#94ae0a',
                                            '#a61120',
                                            '#ff8809',
                                            '#ffd13e',
                                            '#a61187',
                                            '#24ad9a',
                                            '#7c7474',
                                            '#a66111'
                                        ],
                                        insetPadding:0,
                                        bind: {
                                            store: '{dashboardfulllinechartstore}'
                                        },
                                        innerPadding: { top : 10, left: 0, bottom: 0, right : 0 },
                                        series: [
                                            {
                                                type: 'line',
                                                colors: [
                                                    'rgba(103, 144, 199, 0.6)'
                                                ],
                                                xField: 'xvalue',
                                                yField: [
                                                    'y1value'
                                                ],
                                                fill: true
                                                // smooth: true
                                            },
                                            {
                                                type: 'line',
                                                colors: [
                                                    'rgba(238, 146, 156, 0.6)'
                                                ],
                                                xField: 'xvalue',
                                                yField: [
                                                    'y2value'
                                                ],
                                                fill: true
                                                // smooth: true
                                            }
                                        ],
                                        interactions: [
                                            {
                                                type: 'panzoom'
                                            }
                                        ],
                                        axes: [
                                            {
                                                type: 'category',
                                                fields: [
                                                    'xvalue'
                                                ],
                                                hidden: true,
                                                position: 'bottom'
                                            },
                                            {
                                                type: 'numeric',
                                                fields: [
                                                    'y1value',
                                                    'y2value',
                                                    'y3value'
                                                ],
                                                grid: {
                                                    odd: {
                                                        fill: '#e8e8e8'
                                                    }
                                                },
                                                hidden: true,
                                                position: 'left'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'quick-graph-panel',
                                height: 300,
                                // ui: 'light', 
                                margin:10,   
                                layout: 'fit',
                                headerPosition: 'bottom',
                                iconCls: 'fa fa-bar-chart',
                                manageHeight: false,
                                title: 'Bar Chart',
                                bodyPadding:15,
                                items: [
                                    {
                                        xtype: 'cartesian',
                                        colors: [
                                            '#6aa5db',
                                            '#94ae0a',
                                            '#a61120',
                                            '#ff8809',
                                            '#ffd13e',
                                            '#a61187',
                                            '#24ad9a',
                                            '#7c7474',
                                            '#a66111'
                                        ],
                                        insetPadding:0,
                                        bind: {
                                            store: '{marketshareoneyear}'
                                        },
                                        axes: [
                                            {
                                                type: 'category',
                                                fields: [
                                                    'xvalue'
                                                ],
                                                hidden: true,
                                                position: 'bottom'
                                            },
                                            {
                                                type: 'numeric',
                                                fields: [
                                                    'yvalue'
                                                ],
                                                grid: {
                                                    odd: {
                                                        fill: '#e8e8e8'
                                                    }
                                                },
                                                hidden: true,
                                                position: 'left'
                                            }
                                        ],
                                        series: [
                                            {
                                                type: 'bar',
                                                xField: 'xvalue',
                                                yField: [
                                                    'yvalue'
                                                ]
                                            }
                                        ],
                                        interactions: [
                                            {
                                                type: 'panzoom'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                cls: 'right-part',
                items: [
                    {
                        xtype: 'container',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'quick-graph-panel',
                                height: 300,
                                // ui: 'light', 
                                margin:10,   
                                layout: 'fit',
                                headerPosition: 'bottom',
                                iconCls: 'fa fa-line-chart',
                                manageHeight: false,
                                title: 'Line Chart',
                                bodyPadding:15,
                                items: [
                                    {
                                        xtype: 'cartesian',
                                        colors: [
                                            '#6aa5db',
                                            '#94ae0a',
                                            '#a61120',
                                            '#ff8809',
                                            '#ffd13e',
                                            '#a61187',
                                            '#24ad9a',
                                            '#7c7474',
                                            '#a66111'
                                        ],
                                        insetPadding:0,
                                        bind: {
                                            store: '{marketshareoneentitystore}'
                                        },
                                        axes: [
                                            {
                                                type: 'category',
                                                fields: [
                                                    'xvalue'
                                                ],
                                                hidden: true,
                                                position: 'bottom'
                                            },
                                            {
                                                type: 'numeric',
                                                fields: [
                                                    'yvalue',
                                                    'y1value',
                                                    'y2value',
                                                    'y3value',
                                                    'y4value',
                                                    'y5value'
                                                ],
                                                hidden: true,
                                                position: 'left'
                                            }
                                    ],
                                    series: [
                                        {
                                            type: 'line',
                                            xField: 'xvalue',
                                            yField: [
                                                'yvalue'
                                            ]
                                        },
                                        {
                                            type: 'line',
                                            xField: 'xvalue',
                                            yField: [
                                                'y1value'
                                            ]
                                        },
                                       
                                    ],
                                    interactions: [
                                        {
                                            type: 'panzoom'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'quick-graph-panel',
                            height: 300,
                            // ui: 'light', 
                            margin:10,   
                            layout: 'fit',
                            headerPosition: 'bottom',
                            iconCls: 'fa fa-bar-chart',
                            manageHeight: false,
                            title: 'Stacked Bar Chart',
                            bodyPadding:15,
                            items: [
                                {
                                    xtype: 'cartesian',
                                    colors: [
                                        '#6aa5db',
                                        '#ee929c'
                                    ],
                                    insetPadding:0,
                                    bind: {
                                        store: '{marketsharemultiyear}'
                                    },
                                    axes: [
                                        {
                                            type: 'category',
                                            fields: [
                                                'xvalue'
                                            ],
                                            hidden: true,
                                            position: 'bottom'
                                        },
                                        {
                                            type: 'numeric',
                                            fields: [
                                                'y1value',
                                                'y2value',
                                                'y3value'
                                            ],
                                            grid: {
                                                odd: {
                                                    fill: '#e8e8e8'
                                                }
                                            },
                                            hidden: true,
                                            position: 'left'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'bar',
                                            xField: 'xvalue',
                                            yField: [
                                                'y2value',
                                                'y3value'
                                            ]
                                        }
                                    ],
                                    interactions: [
                                        {
                                            type: 'panzoom'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
},
{
    xtype: 'container',
    cls: 'responsive-page-row',
    layout: 'anchor',
    items: [
        {
            xtype: 'container',
            cls: 'left-part',
            items: [
                {
                    xtype: 'container',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'panel',
                            cls: 'quick-graph-panel',
                            height: 300,
                            // ui: 'light', 
                            margin:10,   
                            layout: 'fit',
                            headerPosition: 'bottom',
                            iconCls: 'fa fa-pie-chart',
                            manageHeight: false,
                            title: '2D Pie Chart',
                            bodyPadding:15,
                            items: [
                                {
                                    xtype: 'polar',
                                    colors: [
                                        '#aed581',
                                        '#6aa5db',
                                        '#ee929c'
                                    ],
                                    insetPadding:0,
                                    bind: {
                                        store: '{piedatastore}'
                                    },
                                    series: [
                                        {
                                            type: 'pie',
                                            label: {
                                                field: 'xvalue',
                                                display: 'rotate',
                                                contrast: true,
                                                font: '12px Arial'
                                            },
                                            xField: 'yvalue'
                                        }
                                    ],
                                    interactions: [
                                        {
                                            type: 'rotate'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'quick-graph-panel',
                            height: 300,
                            // ui: 'light', 
                            margin:10,   
                            layout: 'fit',
                            headerPosition: 'bottom',
                            iconCls: 'fa fa-wifi',
                            manageHeight: false,
                            title: 'Gauge Chart',
                            bodyPadding:15,
                            items: [
                                {
                                    xtype: 'polar',
                                    colors: [
                                        '#6aa5db',
                                        '#aed581',
                                        '#a61120',
                                        '#ff8809',
                                        '#ffd13e',
                                        '#a61187',
                                        '#24ad9a',
                                        '#7c7474',
                                        '#a66111'
                                    ],
                                    insetPadding:0,
                                    bind: {
                                        store: '{gaugechartstore}'
                                    },
                                    series: [
                                        {
                                            type: 'gauge',
                                            angleField: 'position',
                                            needleLength: 100
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'right-part',
            items: [
                {
                    xtype: 'container',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'panel',
                            cls: 'quick-graph-panel',
                            height: 300,
                            // ui: 'light', 
                            margin:10,   
                            layout: 'fit',
                            headerPosition: 'bottom',
                            iconCls: 'fa fa-pie-chart',
                            manageHeight: false,
                            title: '3D Pie Chart',
                            bodyPadding:15,
                            items: [
                                {
                                    xtype: 'polar',
                                    colors: [
                                        '#aed581',
                                        '#6aa5db',
                                        '#ee929c'
                                    ],
                                    insetPadding:0,
                                    bind: {
                                        store: '{piedatastore}'
                                    },
                                    series: [
                                        {
                                            type: 'pie3d',
                                            xField: 'yvalue'
                                        }
                                    ],
                                    interactions: [
                                        {
                                            type: 'rotatePie3d'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'quick-graph-panel',
                            height: 300,
                            // ui: 'light', 
                            margin:10,   
                            layout: 'fit',
                            headerPosition: 'bottom',
                            iconCls: 'fa fa-dot-circle-o',
                            manageHeight: false,
                            title: 'Radial Chart',
                            bodyPadding:15,
                            items: [
                                {
                                    xtype: 'polar',
                                    colors: [
                                        '#6aa5db',
                                        '#94ae0a',
                                        '#a61120',
                                        '#ff8809',
                                        '#ffd13e',
                                        '#a61187',
                                        '#24ad9a',
                                        '#7c7474',
                                        '#a66111'
                                    ],
                                    insetPadding:20,
                                    bind: {
                                        store: '{radialchartstore}'
                                    },
                                    axes: [
                                        {
                                            type: 'numeric',
                                            fields: [
                                                'yvalue'
                                            ],
                                            grid: true,
                                            position: 'radial'
                                        },
                                        {
                                            type: 'category',
                                            fields: [
                                                'xvalue'
                                            ],
                                            grid: true,
                                            position: 'angular'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'radar',
                                            xField: 'xvalue',
                                            yField: 'yvalue'
                                        }
                                    ],
                                    interactions: [
                                        {
                                            type: 'rotate'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
]

});
