/*
 * File: app/view/charts/ResponsiveCellContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.charts.ResponsiveCellContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.chartsresponsivecellcontainer',

    requires: [
        'Ext.panel.Panel'
    ],

    cls: 'responsive-cell-container',
    height: 250,

    items: [
        {
            xtype: 'panel',
            height: 250,
            layout: 'fit',
            headerPosition: 'bottom',
            title: 'ChartWithFooter'
        }
    ]

});