/*
 * File: app/view/layouts/LayoutsContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.layouts.LayoutsContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.layoutslayoutscontainer',

    requires: [
        'SenchaDash.view.layouts.LayoutsContainerViewModel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'layoutslayoutscontainer'
    },
    cls:'layouts-wrap',
    items: [
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 380,
                                    ui: 'widget-panel',
                                    width: 250,
                                    layout: 'absolute',
                                    bodyPadding: 20,
                                    title: 'Layouts - Absolute Layout',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            x: 50,
                                            y: 50,
                                            height: 100,
                                            ui: 'widget-panel',
                                            width: 200,
                                            title: 'Panel 1'
                                        },
                                        {
                                            xtype: 'panel',
                                            x: 125,
                                            y: 125,
                                            height: 100,
                                            ui: 'widget-panel',
                                            width: 200,
                                            title: 'Panel 2'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    cls: 'border-layout',
                                    height: 380,
                                    ui: 'widget-panel',
                                    width: 250,
                                    defaults: {
                                        collapsible: true,
                                        split: true,
                                        bodyPadding: 10
                                    },
                                    layout: 'border',
                                    bodyBorder: false,
                                    bodyPadding: 20,
                                    title: 'Layouts - Border Layout',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            collapseMode: 'header',
                                            region: 'south',
                                            height: 70,
                                            html: '<div>Footer content</div>',
                                            maxHeight: 150,
                                            minHeight: 50,
                                            defaults: {
                                                collapsible: true,
                                                split: true,
                                                bodyPadding: 10
                                            },
                                            collapsible: false,
                                            title: 'Footer',
                                            titleAlign: 'center',
                                            titleCollapse: false
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'west',
                                            html: '<p>Secondary content like navigation links could go here</p>',
                                            width: 125,
                                            collapsible: false,
                                            title: 'Navigation'
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            html: '<h2>Main Page</h2><p>This is where the main content would go</p>',
                                            collapsible: false,
                                            title: 'Main Content'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    cls: 'accordian-layout',
                                    height: 250,
                                    ui: 'widget-panel',
                                    width: 250,
                                    defaults: {
                                        collapsible: true,
                                        split: true,
                                        bodyPadding: 10
                                    },
                                    layout: 'accordion',
                                    bodyBorder: false,
                                    bodyPadding: 20,
                                    title: 'Layouts - Accordion Layout',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 70,
                                            html: '<p>Footer content</p>',
                                            maxHeight: 75,
                                            minHeight: 65,
                                            defaults: {
                                                collapsible: true,
                                                split: true,
                                                bodyPadding: 10
                                            },
                                            collapsible: false,
                                            title: 'First Item',
                                        },
                                        {
                                            xtype: 'panel',
                                            html: '<p>Secondary content like navigation links could go here</p>',
                                            width: 125,
                                            collapsible: false,
                                            title: 'Second Item'
                                        },
                                        {
                                            xtype: 'panel',
                                            html: '<h2>Main Page</h2><p>This is where the main content would go</p>',
                                            collapsible: false,
                                            title: 'Third Item'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 250,
                                    ui: 'widget-panel',
                                    width: 250,
                                    defaults: {
                                        collapsible: true,
                                        split: true,
                                        bodyPadding: 10
                                    },
                                    layout: 'column',
                                    bodyBorder: false,
                                    bodyPadding: 10,
                                    title: 'Layouts - Column Layout',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            columnWidth: 0.33,
                                            height: 175,
                                            html: '<p>Footer content</p>',
                                            ui: 'widget-panel',
                                            defaults: {
                                                collapsible: true,
                                                split: true,
                                                bodyPadding: 10
                                            },
                                            bodyPadding: 10,
                                            collapsible: false,
                                            title: 'First Item',
                                            titleCollapse: false
                                        },
                                        {
                                            xtype: 'panel',
                                            columnWidth: 0.33,
                                            height: 175,
                                            html: '<p>Secondary content like navigation links could go here</p>',
                                            ui: 'widget-panel',
                                            bodyPadding: 10,
                                            collapsible: false,
                                            title: 'Second Item'
                                        },
                                        {
                                            xtype: 'panel',
                                            columnWidth: 0.34,
                                            height: 175,
                                            html: '<p>This is where the main content would go</p>',
                                            ui: 'widget-panel',
                                            bodyPadding: 10,
                                            collapsible: false,
                                            title: 'Third Item'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 250,
                                    ui: 'widget-panel',
                                    width: 250,
                                    defaults: {
                                        collapsible: true,
                                        split: true,
                                        bodyPadding: 10
                                    },
                                    layout: 'fit',
                                    bodyBorder: false,
                                    bodyPadding: 10,
                                    title: 'Layouts - Fit Layout',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            height: 200,
                                            html: '<p>This panel is fit within its container.</p>',
                                            ui: 'widget-panel',
                                            defaults: {
                                                collapsible: true,
                                                split: true,
                                                bodyPadding: 10
                                            },
                                            bodyBorder: false,
                                            collapsible: false,
                                            title: 'Inner Panel',
                                            titleCollapse: false
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    showNext: function() {
                                        this.doCardNavigation(1);
                                    },
                                    showPrevious: function() {
                                        this.doCardNavigation(-1);
                                    },
                                    doCardNavigation: function(incr) {
                                        var me = this;
                                        var l = me.getLayout();
                                        var i = l.activeItem.id.split('card-')[1];
                                        var next = parseInt(i, 10) + incr;
                                        l.setActiveItem(next);

                                        me.down('#card-prev').setDisabled(next===0);
                                        me.down('#card-next').setDisabled(next===2);
                                    },
                                    items: [
                                        {
                                            id: 'card-0',
                                            html: '<div class="card-inner-div"><h2>Welcome to the Demo Wizard!</h2><p>Step 1 of 3</p><p>Please click the "Next" button to continue...</p></div>'
                                        },
                                        {
                                            id: 'card-1',
                                            html: '<div class="card-inner-div">Step 2 of 3</p><p>Almost there.  Please click the "Next" button to continue...</div>'
                                        },
                                        {
                                            id: 'card-2',
                                            html: '<div class="card-inner-div"><h1>Congratulations!</h1><p>Step 3 of 3 - Complete</p></div>'
                                        }
                                    ],
                                    bbar: [
                                        '->',
                                        {
                                            itemId: 'card-prev',
                                            text: '&laquo; Previous',
                                            handler: 'showPrevious',
                                            disabled: true,
                                            margin:0,
                                            cls:'previous-btn'
                                        },
                                        {
                                            itemId: 'card-next',
                                            text: 'Next &raquo;',
                                            handler: 'showNext',
                                            margin:'0 20 20 15',
                                            cls:'next-btn'
                                        }
                                    ],
                                    defaultListenerScope: true,
                                    // cls: 'accordian-layout',
                                    height: 250,
                                    ui: 'widget-panel',
                                    width: 250,
                                    layout: 'card',
                                    bodyBorder: false,
                                    bodyPadding: 20,
                                    title: 'Layouts - Card Layout'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 300,
                                    ui: 'widget-panel',
                                    bodyPadding: 10,
                                    title: 'Layouts - VBox Layout',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            ui: 'widget-panel',
                                            title: 'Panel 1'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            ui: 'widget-panel',
                                            title: 'Panel 2'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            // cls: 'accordian-layout',
                                            ui: 'widget-panel',
                                            title: 'Panel 3'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 300,
                                    ui: 'widget-panel',
                                    bodyPadding: 10,
                                    title: 'Layouts - HBox Layout',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            ui: 'widget-panel',
                                            title: 'Panel 1'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            ui: 'widget-panel',
                                            title: 'Panel 2'
                                        },
                                        {
                                            xtype: 'panel',
                                            flex: 1,
                                            ui: 'widget-panel',
                                            title: 'Panel 3'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});