/*
 * File: app/view/email/FriendsMenu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.email.FriendsMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.emailfriendsmenu',

    requires: [
        'SenchaDash.view.email.FriendsMenuViewModel'
    ],

    viewModel: {
        type: 'emailfriendsmenu'
    },
    floating: false,

    initComponent: function() {
        var me=this;
        me.items=[];
        var store=me.getViewModel().getStore("mailfriendstore");
        store.getData().each(function(item, index, totalItems ) {
            var idata=item.data;
            var icls=(idata.online)? 'online-user' : 'offline-user';
            me.items.push({ xtype: 'menuitem', text : idata.name, cls:icls });
        });
        me.callParent(arguments);
    }

});