/*
 * File: app/view/email/MainContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.email.MainContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.emailmaincontainer',
    cls:'email-main-wrap',
    requires: [
        'SenchaDash.view.email.MainContainerViewModel',
        'SenchaDash.view.email.MainContainerViewController',
        'SenchaDash.view.email.FriendsMenu',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.panel.Tool'
    ],

    controller: 'emailmaincontainer',
    viewModel: {
        type: 'emailmaincontainer'
    },
    itemId: 'emailMainContainer',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            //cls: 'email-navigation-menu',
            itemId: 'emailCtnLeftMenuCtn',
            margin:10,
            width: 200,
            items: [
                {
                    xtype: 'panel',
                    cls: 'navigation-email',
                    iconCls: 'fa fa-paper-plane',
                    title: 'Email',
                    //ui:'navigation-email',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            header: false,
                            title: 'Email',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    viewToOpen: 'email.ComposePanel',
                                    itemId: 'viewEmailComposePanel',
                                    iconCls: 'fa fa-edit',
                                    text: 'Compose'
                                },
                                {
                                    xtype: 'menuitem',
                                    viewToOpen: 'email.InboxPanel',
                                    itemId: 'viewEmailInboxPanel',
                                    iconCls: 'fa fa-inbox',
                                    text: 'Inbox'
                                },
                                {
                                    xtype: 'menuitem',
                                    iconCls: 'fa fa-check-circle',
                                    text: 'Sent Mail'
                                },
                                {
                                    xtype: 'menuitem',
                                    iconCls: 'fa fa-exclamation-circle',
                                    text: 'Spam'
                                },
                                {
                                    xtype: 'menuitem',
                                    iconCls: 'fa fa-trash-o',
                                    text: 'Trash'
                                }
                            ],
                            listeners: {
                                click: 'onMenuClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    cls: 'navigation-email',
                    title: 'Friends',                    
                    iconCls:'fa fa-group',
                    items: [
                        {
                            xtype: 'emailfriendsmenu'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            itemId: 'emailRightContainer',
            layout: 'card'
        }
    ]
});