/*
 * File: app/view/email/SingleMailContainerViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.email.SingleMailContainerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.emailsinglemailcontainer',

    onBackBtnClick: function(button, e, eOpts) {
        SenchaDash.app.getController('Navigation').getEmailMainContainer().getController().setCurrentView('SenchaDash.view.email.InboxPanel');
    },

    beforeSingleMailCtnRender: function(component, eOpts) {
        var self = this,
            view = this.getView(),
            record = view.record ? view.record : {},
            mailBodyCtn = view.query("#mailBodyCtn")[0],
            emailSubjectContainer = view.query("#emailSubjectContainer")[0];

        mailBodyCtn.setHtml(record.get("contents")?record.get("contents"): "" );
        emailSubjectContainer.setData(record.data? record.data: {});
        if(! view.record.data.has_attachments)
        view.down('container[type="single-mail-attachment"]').hide()

    }

});
