/*
 * File: app/view/email/SingleMailContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.email.SingleMailContainer', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.emailsinglemailcontainer',

    requires: [
        'SenchaDash.view.email.SingleMailContainerViewModel',
        'SenchaDash.view.email.SingleMailContainerViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.Img',
        'Ext.XTemplate',
        'Ext.panel.Panel',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Spacer'
    ],

    controller: 'emailsinglemailcontainer',
    viewModel: {
        type: 'emailsinglemailcontainer'
    },
    header: false,
    bodyPadding:15,
    margin:10,
    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'toolbar',
            cls: 'single-mail-top-toolbar',
            height: 55,
            maxHeight: 55,
            minHeight: 55,
            items: [
                {
                    xtype: 'button',
                    cls: '',
                    minWidth: 36,
                    width: '',
                    iconCls: 'fa fa-angle-left',
                    text: '',
                    listeners: {
                        click: 'onBackBtnClick'
                    }
                },                
                {
                    xtype: 'button',
                    cls: '',                    
                    minWidth: 36,
                    width: 36,
                    iconCls: 'fa fa-trash',
                   
                },               
                {
                    xtype: 'button',                   
                    minWidth: 36,
                    width: 36,
                    iconCls: 'fa fa-exclamation-circle',
                   
                },
                {
                    xtype: 'button',                    
                    minWidth: 36,
                    width: 36,
                    iconCls:'fa fa-print'
                   
                },
                {
                    xtype: 'button',                   
                    minWidth: 36,
                    width: 36,
                    iconCls: 'fa fa-forward',
                    
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'single-mail-sender-info',
            height: 108,
            layout: {
                type: 'hbox',
                align: 'stretch',
                padding: ''
            },
            items: [
                {
                    xtype: 'container',
                    padding: '15 0 0 0',
                    width: 100,
                    cls:'email-sender-img',
                    items: [
                        {
                            xtype: 'image',
                            height: 80,
                            width: 80,
                            src: 'resources/images/user-profile/7.png'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    cls: 'single-mail-email-subject',
                    data: {
                        from: 'John.Deo@gmail.com',
                        title: 'Important Mail'
                    },
                    itemId: 'emailSubjectContainer',
                    padding: 10,
                    tpl: [
                        '<div class = "user-name"> {from} </div>',
                        '<div class = "user-info"> {title} </div>'
                    ],
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'single-mail-sender-info mail-body',
            html: 'Hi<br/>Are you going to reach on time?',
            itemId: 'mailBodyCtn'
        },
        {
            xtype: 'container',
            flex: 1,
            cls: 'single-mail-sender-info',
            padding:'15 0 0 0',
            items: [
                {
                    xtype: 'container',
                    cls: 'single-mail-attachment',
                    type:'single-mail-attachment',
                    frameHeader: false,
                    iconCls: 'fa fa-link',
                    overlapHeader: false,
                    title: 'Attachments',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            html: '<img src="resources/images/img1.jpg" alt="profile image" height="100" width="100">',
                            padding: '15 15 12 0'
                        },
                        {
                            xtype: 'container',
                            html: '<img src="resources/images/img2.jpg" alt="profile image" height="100" width="100">',
                           padding: '15 15 12 0'
                        },
                        {
                            xtype: 'container',
                            html: '<img src="resources/images/img3.jpg" alt="profile image" height="100" width="100">',
                            padding: '15 15 12 0'
                        },
                        {
                            xtype: 'container',
                            html: '<img src="resources/images/img4.jpg" alt="profile image" height="100" width="100">',
                            padding: '15 15 12 0'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '15 0',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'htmleditor',
                            height: 250,
                            minHeight: 250,
                            fieldLabel: 'Reply',
                            hideLabel: true
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    padding:0,
                    cls: 'single-mail-action-button',
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            cls: 'email-compose-save-button',
                            text: 'Save',
                            margin:'0 0 0 15'
                        },
                        {
                            xtype: 'button',
                            cls: 'email-compose-send-button',
                            text: 'Send',
                            margin:'0 0 0 15'
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'beforeSingleMailCtnRender'
    }

});
