/*
 * File: app/view/main/MessagesPopupWinViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.main.MessagesPopupWinViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.mainmessagespopupwin',

    requires: [
        'Ext.data.Store'
    ],

    stores: {
        messagesstore: {
            model: 'SenchaDash.model.PersonalInfoModel',
            data: [
                {
                    name: 'Andy',
                    status: '15 minutes ago',
                    icon: 'sint'
                },
                {
                    name: 'Lucy',
                    status: '2 hours ago',
                    icon: 'non'
                },
                {
                    name: 'Jackson',
                    status: '2 hours ago',
                    icon: 'debitis'
                },
                {
                    name: 'Linda',
                    status: 'Yesterday',
                    icon: 'sint'
                },
                {
                    name: 'Dona',
                    status: 'Yesterday',
                    icon: 'non'
                },
                {
                    name: 'Jackson',
                    status: '2 hours ago',
                    icon: 'debitis'
                }
            ]
        }
    }

});