/*
 * File: app/view/main/MessagesPopupWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.main.MessagesPopupWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.mainmessagespopupwin',

    requires: [
        'SenchaDash.view.main.MessagesPopupWinViewModel',
        'Ext.view.View',
        'Ext.XTemplate',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'mainmessagespopupwin'
    },
    height: 250,
    width: 254,
    title: 'You have 3 messages',

    items: [
        {
            xtype: 'dataview',
            autoScroll: true,
            itemSelector: '.listItemCls',
            itemTpl: [
                '<div class="listItemCls"> <span> </span><span><div class="nameCls"> {name} sent you a message</div> <div class="statusCls"> {status} </div></span></div>'
            ],
            bind: {
                store: '{messagesstore}'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'label',
                    text: 'Show all messages'
                }
            ]
        }
    ]

});