/*
 * File: app/view/main/NotificationsPopupWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.main.NotificationsPopupWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.mainnotificationspopupwin',

    requires: [
        'SenchaDash.view.main.NotificationsPopupWinViewModel',
        'Ext.form.Label',
        'Ext.ProgressBar',
        'Ext.view.View',
        'Ext.XTemplate',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'mainnotificationspopupwin'
    },
    height: 250,
    width: 254,
    title: 'You have 5 notifications',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'label',
            padding: 5,
            text: 'Database Repair'
        },
        {
            xtype: 'progressbar',
            value: 0.7
        },
        {
            xtype: 'label',
            padding: 5,
            text: 'Upgrade Progress'
        },
        {
            xtype: 'progressbar',
            value: 0.1
        },
        {
            xtype: 'dataview',
            flex: 1,
            autoScroll: true,
            itemSelector: '.listItemCls',
            itemTpl: [
                '<div class="listItemCls"> <span> </span><span><div class="nameCls"> {name} </div> <div class="statusCls"> {status} </div></span></div>'
            ],
            bind: {
                store: '{notificationsstore}'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'label',
                    text: 'Show all notifications'
                }
            ]
        }
    ]

});