/*
 * File: app/view/main/RightNavigationPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.main.RightNavigationPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainrightnavigationpanel',

    requires: [
        'SenchaDash.view.main.RightNavigationPanelViewModel',
        'Ext.tab.Tab',
        'Ext.form.field.Text',
        'Ext.XTemplate',
        'Ext.form.Label',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Template',
        'Ext.grid.column.Check',
        'Ext.ProgressBar',
        'Ext.tab.Bar'
    ],

    viewModel: {
        type: 'mainrightnavigationpanel'
    },
    height: 456,
    ui: 'navigation-light',
    width: 240,
    collapsible: true,
    header: false,
    title: 'Right Panel',
    activeTab: 0,

    items: [
        {
            xtype: 'panel',
            glyph: 72,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            tabConfig: {
                xtype: 'tab',
                minWidth: 80,
                glyph: 'xf086@FontAwesome'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 3,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            height: 20,
                            inputType: 'search',
                            emptyText: 'Freinds'
                        },
                        {
                            xtype: 'dataview',
                            flex: 1,
                            itemSelector: 'div',
                            itemTpl: Ext.create('Ext.XTemplate', 
                                '                               {[this.getFreindsNameString(values)]}  {[this.getConnectionStatusString(values)]}',
                                {
                                    getFreindsNameString: function(values) {
                                        return "<span>" + values.freindsName  + "</span>";
                                    },
                                    getConnectionStatusString: function(values) {
                                        return "<span>" + values.connectionStatus  + "</span>";
                                    }
                                }
                            ),
                            bind: {
                                store: '{FreindsStore}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 2,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'dataview',
                            flex: 1,
                            itemSelector: 'div',
                            itemTpl: Ext.create('Ext.XTemplate', 
                                '{[this.getChatString(values)]}',
                                {
                                    getChatString: function(values) {

                                        var color = values.sender === 'user' ? 'red' : 'blue';
                                        var float_dir = values.sender === 'user' ? 'right':'left';


                                        var stringToReturn ='';
                                        stringToReturn += '<span ';




                                        stringToReturn += ' style=';
                                        stringToReturn += 'color:' + color;
                                        stringToReturn += ';';


                                        stringToReturn +=' >';
                                        stringToReturn += values.message;
                                        stringToReturn += '</span>';

                                        return stringToReturn;

                                    }
                                }
                            ),
                            bind: {
                                store: '{ChatStore}'
                            }
                        },
                        {
                            xtype: 'textfield',
                            hideLabel: true,
                            emptyText: 'Chat Here',
                            enableKeyEvents: true
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            glyph: 72,
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            tabConfig: {
                xtype: 'tab',
                minWidth: 80,
                glyph: 'xf086@FontAwesome'
            },
            items: [
                {
                    xtype: 'label',
                    flex: 1,
                    cls: 'listHeaderCls',
                    maxHeight: 40,
                    text: 'Family'
                },
                {
                    xtype: 'dataview',
                    flex: 1,
                    height: 100,
                    itemId: 'FamilyDataView',
                    itemSelector: '.listItemCls',
                    itemTpl: [
                        '<div class="listItemCls"> <span> </span><span><div class="nameCls"><b> {name} </b></div> <div class="statusCls"> <b>{status} </b></div></span></div>'
                    ],
                    bind: {
                        store: '{familystore}'
                    }
                },
                {
                    xtype: 'label',
                    flex: 1,
                    cls: 'listHeaderCls',
                    maxHeight: 40,
                    text: 'Friends'
                },
                {
                    xtype: 'dataview',
                    flex: 1,
                    height: 100,
                    itemId: 'FriendsDataView',
                    itemSelector: '.listItemCls',
                    itemTpl: [
                        '<div class="listItemCls"> <span> </span><span><div class="nameCls"> <b>{name} </b></div> <div class="statusCls"> <b>{status} </b></div></span></div>'
                    ],
                    bind: {
                        store: '{friendsstore}'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            tabConfig: {
                xtype: 'tab',
                minWidth: 80,
                glyph: 'xf05a@FontAwesome'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    maxHeight: 100,
                    padding: 10,
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            text: 'Monthly Billing'
                        },
                        {
                            xtype: 'label',
                            text: 'December 2014'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            maxHeight: 30,
                            text: 'Pay Now'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    maxHeight: 100,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            width: '',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: '',
                                    maxHeight: 20,
                                    text: '4,327'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    maxHeight: 20,
                                    text: 'SALES'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            width: '',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    height: '',
                                    maxHeight: 20,
                                    text: '$1,252'
                                },
                                {
                                    xtype: 'label',
                                    flex: 1,
                                    maxHeight: 20,
                                    text: 'EARNING'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    header: false,
                    title: 'My Grid Panel',
                    forceFit: true,
                    hideHeaders: true,
                    bind: {
                        store: '{rightpanelfeaturestore}'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'String',
                            flex: 2
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'status',
                            text: 'MyColumn1',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'label',
                            text: 'Questions?'
                        },
                        {
                            xtype: 'label',
                            text: ' (415) 234-53454 '
                        },
                        {
                            xtype: 'label',
                            text: 'We are here 24/7'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            title: '',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            tabConfig: {
                xtype: 'tab',
                minWidth: 80,
                glyph: 'xf013@FontAwesome'
            },
            items: [
                {
                    xtype: 'label',
                    cls: 'listHeaderCls',
                    text: 'Account Settings'
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    maxHeight: 130,
                    header: false,
                    manageHeight: false,
                    title: 'My Grid Panel',
                    hideHeaders: true,
                    bind: {
                        store: '{accountsettingsstore}'
                    },
                    columns: [
                        {
                            xtype: 'templatecolumn',
                            tpl: [
                                '<div> {title} </div> <div> {subTitle} </div>'
                            ],
                            dataIndex: 'string',
                            text: 'String',
                            flex: 1
                        },
                        {
                            xtype: 'checkcolumn',
                            maxWidth: 35,
                            dataIndex: 'toggleStatus',
                            text: 'Boolean'
                        }
                    ]
                },
                {
                    xtype: 'label',
                    cls: 'listHeaderCls',
                    text: 'Public Settings'
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    maxHeight: 90,
                    header: false,
                    manageHeight: false,
                    title: 'My Grid Panel',
                    hideHeaders: true,
                    bind: {
                        store: '{publicsettingsstore}'
                    },
                    columns: [
                        {
                            xtype: 'templatecolumn',
                            tpl: [
                                '<div> {title} </div> '
                            ],
                            dataIndex: 'string',
                            text: 'String',
                            flex: 1
                        },
                        {
                            xtype: 'checkcolumn',
                            maxWidth: 35,
                            dataIndex: 'toggleStatus',
                            text: 'Boolean'
                        }
                    ]
                },
                {
                    xtype: 'label',
                    cls: 'listHeaderCls',
                    text: 'Task Progress'
                },
                {
                    xtype: 'progressbar',
                    value: 0.4
                }
            ]
        }
    ],
    tabBar: {
        xtype: 'tabbar',
        height: 45
    }

});