/*
 * File: app/view/forms/GeneralContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.forms.GeneralContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.formsgeneralcontainer',

    requires: [
        'SenchaDash.view.forms.GeneralContainerViewModel',
        'Ext.form.Panel',
        'Ext.toolbar.Spacer',
        'Ext.form.field.TextArea',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.File',
        'Ext.form.field.FileButton',
        'Ext.slider.Single'
    ],

    viewModel: {
        type: 'formsgeneralcontainer'
    },
    cls: 'coditas-forms-page',

    items: [
        {
            xtype: 'container',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    cls: 'form-panel',
                    ui: 'widget-panel',
                    bodyPadding: '20',
                    title: 'Inline Form',
                    titleCollapse: false,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            cls: 'textfield',
                            height: 32,
                            maxHeight: 32,
                            width: 200,
                            labelPad: 10,
                            inputType: 'email',
                            emptyText: 'Enter Email'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            cls: 'textfield',
                            height: 32,
                            maxHeight: 32,
                            width: 200,
                            labelPad: 10,
                            inputType: 'password',
                            emptyText: 'Password'
                        },
                        {
                            xtype: 'checkboxfield',
                            flex: 1,
                            cls: 'form-panel-font-color',
                            height: 32,
                            maxHeight: 32,
                            boxLabel: 'Remember me'
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            cls: 'form-panel-button',
                            text: 'Sign In'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'form',
                                    cls: 'form-panel blocked-style-form',
                                    height: 277,
                                    ui: 'widget-panel',
                                    bodyPadding: '20',
                                    title: 'Block Styled Form',
                                    layout: {
                                        type: 'table',
                                        columns: 2
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            cls: 'textfield',
                                            height: 32,
                                            width: '95%',
                                            fieldLabel: 'Firstname',
                                            labelAlign: 'top',
                                            labelPad: 2
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'textfield',
                                            height: 32,
                                            width: '100%',
                                            fieldLabel: 'Lastname',
                                            labelAlign: 'top',
                                            labelPad: 1
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'textfield',
                                            height: 32,
                                            width: '95%',
                                            fieldLabel: 'Email',
                                            labelAlign: 'top',
                                            inputType: 'email'
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'textfield',
                                            height: 32,
                                            width: '100%',
                                            fieldLabel: 'Website',
                                            labelAlign: 'top'
                                        },
                                        {
                                            xtype: 'tbspacer'
                                        },
                                        {
                                            xtype: 'button',
                                            cls: 'form-panel-button',
                                            text: 'Submit',
                                            margin:'8 0 0 0'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'form',
                                    cls: 'form-panel horizontal-form',
                                    height: 277,
                                    ui: 'widget-panel',
                                    bodyPadding: 20,
                                    title: 'Horizontal Form',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            cls: 'textfield',
                                            height: 32,
                                            fieldLabel: 'Email',
                                            labelWidth: 80,
                                            inputType: 'email'
                                        },
                                        {
                                            xtype: 'textfield',
                                            cls: 'textfield',
                                            height: 32,
                                            width: '100%',
                                            fieldLabel: 'Password',
                                            labelWidth: 80,
                                            inputType: 'password'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            margin: '0 0 0 85',
                                            flex:1,
                                            padding: '0 0 0 100',
                                            boxLabel: 'Remember me'
                                        },
                                        {
                                            xtype: 'button',
                                            cls: 'form-panel-button',
                                            text: 'Sign In'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'form',
                                    height: 325,
                                    ui: 'widget-panel',
                                    bodyPadding: 20,
                                    title: 'No Label Form - Block Style',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            cls: 'form-panel-border',
                                            height: 32,
                                            minHeight: 32,
                                            width: '90%',
                                            labelSeparator: '',
                                            labelWidth: 80,
                                            emptyText: 'Name'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            cls: 'form-panel-border',
                                            height: 32,
                                            minHeight: 32,
                                            width: '90%',
                                            labelSeparator: '',
                                            labelWidth: 80,
                                            emptyText: 'Email'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            cls: 'form-panel-border',
                                            height: 32,
                                            minHeight: 32,
                                            width: '90%',
                                            labelSeparator: '',
                                            labelWidth: 80,
                                            emptyText: 'Address'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            cls: 'form-panel-border',
                                            height: 32,
                                            minHeight: 32,
                                            width: '90%',
                                            labelSeparator: '',
                                            labelWidth: 80,
                                            emptyText: 'Website'
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            margin: '10 0 0 0',
                                            items: [
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'form-panel-button',
                                                    margin: '0 10 0 0',
                                                    text: 'Login'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'form-panel-reset-button',
                                                    margin: '0 0 0 0',
                                                    text: 'Reset'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'form',
                                    height: 325,
                                    ui: 'widget-panel',
                                    bodyPadding: 20,
                                    title: 'No Label Form - Inline',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 35,
                                            margin: '0 0 10 0',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margins: '',
                                                    height: 32,
                                                    margin: '0 15 0 0',
                                                    minHeight: 32,
                                                    emptyText: 'Name'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    height: 32,
                                                    margin: '0 15 0 0',
                                                    minHeight: 32,
                                                    emptyText: 'Email'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    height: 32,
                                                    minHeight: 32,
                                                    emptyText: 'Website'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'textareafield',
                                            flex: 1,
                                            cls: 'no-label-form',
                                            height: 135,
                                            minHeight: 135,
                                            emptyText: 'Message'
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'form-panel-button',
                                                    text: 'Send message'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'form',
                                    cls: 'form-panel',
                                    height: 475,
                                    ui: 'widget-panel',
                                    bodyPadding: '20 20 10 20',
                                    title: 'Basic Form Elements',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'Text Input',
                                            labelWidth: 80,
                                            emptyText: 'Text'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'Email Input',
                                            labelWidth: 80,
                                            inputType: 'email',
                                            emptyText: 'Enter your email'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'Password',
                                            labelWidth: 80,
                                            inputType: 'password',
                                            emptyText: 'Password'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'Readonly',
                                            labelWidth: 80,
                                            readOnly: true,
                                            emptyText: 'Readonly input here..'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            flex: 1,
                                            fieldLabel: 'Textarea',
                                            labelWidth: 80,
                                            emptyText: 'Your comments here..'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'table',
                                                columns: 1
                                            },
                                            items: [
                                                {
                                                    xtype: 'radiogroup',
                                                    padding: '10 0 0 0',
                                                    width: 400,
                                                    fieldLabel: 'Radio',
                                                    labelWidth: 80,
                                                    items: [
                                                        {
                                                            xtype: 'radiofield',
                                                            width: 100,
                                                            labelWidth: 80,
                                                            name: 'inlineGroupOneRadioButton',
                                                            boxLabel: 'Option 1',
                                                            checked: true
                                                        },
                                                        {
                                                            xtype: 'radiofield',
                                                            width: 100,
                                                            labelWidth: 80,
                                                            name: 'inlineGroupOneRadioButton',
                                                            boxLabel: 'Option 2'
                                                        },
                                                        {
                                                            xtype: 'radiofield',
                                                            width: 100,
                                                            labelWidth: 80,
                                                            name: 'inlineGroupOneRadioButton',
                                                            boxLabel: 'Option 3'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'table',
                                                columns: 1
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxgroup',
                                                    padding: '10 0 0 0',
                                                    width: 400,
                                                    fieldLabel: 'Checkbox',
                                                    labelWidth: 80,
                                                    items: [
                                                        {
                                                            xtype: 'checkboxfield',
                                                            width: 100,
                                                            labelWidth: 80,
                                                            name: 'inlineGroupOneCheckbox',
                                                            boxLabel: 'Option 1',
                                                            checked: true
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            width: 100,
                                                            labelWidth: 80,
                                                            name: 'inlineGroupOneCheckbox',
                                                            boxLabel: 'Option 2'
                                                        },
                                                        {
                                                            xtype: 'checkboxfield',
                                                            width: 100,
                                                            labelWidth: 80,
                                                            name: 'inlineGroupOneCheckbox',
                                                            boxLabel: 'Option 3'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'filefield',
                                            padding: '20 0 0 0',
                                            width: 340,
                                            fieldLabel: 'File Input',
                                            labelCls: 'x-form-item-label attach-form-label',
                                            labelPad: 10,
                                            labelSeparator: ':',
                                            labelWidth: 80,
                                            buttonOnly: true,
                                            buttonText: '',
                                            buttonConfig: {
                                                xtype: 'filebutton',
                                                cls: 'x-form-file-btn cloud-upload',
                                                margin: '0 0 0 20',
                                                iconCls: 'fa fa-cloud-upload',
                                                text: 'Choose File',
                                                textAlign: 'left'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'form',
                                    cls: 'form-panel',
                                    height: 487,
                                    ui: 'widget-panel',
                                    bodyPadding: 15,
                                    title: 'Range Slider component',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldcontainer',
                                            flex: 1,
                                            padding: 10,
                                            width: 400,
                                            labelAlign: 'top',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'slider',
                                                    flex: 1,
                                                    cls: 'slider-default',
                                                    width: 400,
                                                    fieldLabel: 'Default',
                                                    hideEmptyLabel: false,
                                                    labelAlign: 'top',
                                                    value: 90
                                                },
                                                {
                                                    xtype: 'slider',
                                                    flex: 1,
                                                    cls: 'slider-hover',
                                                    width: 400,
                                                    fieldLabel: 'Hover',
                                                    labelAlign: 'top'
                                                },
                                                {
                                                    xtype: 'slider',
                                                    flex: 1,
                                                    cls: 'slider-drag',
                                                    width: 400,
                                                    fieldLabel: 'Drag',
                                                    labelAlign: 'top'
                                                },
                                                {
                                                    xtype: 'slider',
                                                    flex: 1,
                                                    cls: 'slider-focus',
                                                    width: 400,
                                                    fieldLabel: 'Focus',
                                                    labelAlign: 'top',
                                                    value: 50
                                                },
                                                {
                                                    xtype: 'slider',
                                                    flex: 1,
                                                    cls: 'slider-focus-hover',
                                                    width: 400,
                                                    fieldLabel: 'Focussed Hover',
                                                    labelAlign: 'top',
                                                    value: 59
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            flex: 1,
                                            cls: 'vertical-slider',
                                            padding: 10,
                                            labelAlign: 'top',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'slider',
                                                    flex: 1,
                                                    height: 400,
                                                    padding: 20,
                                                    fieldLabel: 'Default',
                                                    labelAlign: 'top',
                                                    value: 75,
                                                    vertical: true
                                                },
                                                {
                                                    xtype: 'slider',
                                                    flex: 1,
                                                    height: 400,
                                                    padding: 20,
                                                    fieldLabel: 'Step',
                                                    labelAlign: 'top',
                                                    value: 76,
                                                    increment: 10,
                                                    keyIncrement: 10,
                                                    vertical: true
                                                },
                                                {
                                                    xtype: 'multislider',
                                                    flex: 1,
                                                    height: 400,
                                                    padding: 20,
                                                    fieldLabel: 'Range',
                                                    labelAlign: 'top',
                                                    value: 82,
                                                    values: [
                                                        10,
                                                        82
                                                    ],
                                                    vertical: true
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});