/*
 * File: app/view/forms/WizardContianer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.forms.WizardContianer', {
    extend: 'Ext.container.Container',
    alias: 'widget.formswizardcontianer',

    requires: [
        'SenchaDash.view.forms.WizardContianerViewModel',
        'SenchaDash.view.forms.WizardContianerViewController',
        'Ext.form.Panel',
        'Ext.XTemplate',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.toolbar.Spacer',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea',
        'Ext.ProgressBar'
    ],

    controller: 'formswizardcontianer',
    viewModel: {
        type: 'formswizardcontianer'
    },
    cls: 'coditas-forms-page',
    renderData: [
        {
            id: 10,
            value: 'Automobile'
        },
        {
            id: 24,
            value: 'Autocomplete'
        }
    ],
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            header: false,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'form',
                                    cls: 'form-panel widget-top-container',
                                    height: 390,
                                    minHeight: 390,
                                    ui: 'widget-panel',
                                    bodyPadding: 15,
                                    header: false,
                                    title: 'Basic Validation',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            cls: 'wizard-register-inner-container',
                                            data: {
                                                title: 'Register Today',
                                                img: 'resources/images/friends/f1.png',
                                                msg: 'Members have free access to 100 high resolution images for downloading every week.'
                                            },
                                            padding: '100 50 20 50',
                                            tpl: [
                                                '<span class=\'wizard-register-header\'>{title}</span><br/>',
                                                '<img src="{img}" class="registration_message_image" /><br/>',
                                                '{msg}'
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            cls: 'wizard-register-button-container',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    maxWidth: 150,
                                                    minWidth: 150,
                                                    width: '50px',
                                                    iconCls: 'fa fa-arrow-right',
                                                    text: 'Learn More....'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    cls: 'wizard-top-right-tab-panel',
                    height: 390,
                    itemId: 'wizardFirstFormAccountTabPanel',
                    minHeight: 390,
                    ui: 'widget-panel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            cls: 'form-panel',
                            bodyPadding: '15 15 15 15',
                            iconAlign: 'top',
                            iconCls: 'fa fa-user-plus',
                            title: 'Account',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            tabConfig: {
                                xtype: 'tab',
                                width: 100
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormUsernameTextField',
                                    fieldLabel: 'Username',
                                    emptyText: 'Username'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormEmailTextField',
                                    fieldLabel: 'Email',
                                    emptyText: 'Email'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormPasswordTextField',
                                    fieldLabel: 'Password',
                                    inputType: 'password',
                                    emptyText: 'Password'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormRetypePasswordTextField',
                                    fieldLabel: 'Password',
                                    inputType: 'password',
                                    emptyText: 'Retype Password'
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '0 15',
                                            text: 'Previous'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'wizardFirstFormNextButton',
                                            text: 'Next',
                                            listeners: {
                                                click: {
                                                    fn: 'onWizardFirstFormNextButtonClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'form-panel',
                            bodyPadding: '15 15 15 15',
                            iconAlign: 'top',
                            iconCls: 'fa fa-user',
                            title: 'Profile',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            tabConfig: {
                                xtype: 'tab',
                                width: 100
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'First Name',
                                    emptyText: 'First name'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Last Name',
                                    emptyText: 'Last name'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Company',
                                    emptyText: 'Company'
                                },
                                {
                                    xtype: 'radiogroup',
                                    padding: '-1 0 15 0',
                                    width: 400,
                                    fieldLabel: 'Membership',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            flex: 1,
                                            padding: '7 0 0 0',
                                            name: 'wizardFirstMemberType',
                                            boxLabel: 'Business'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            flex: 1,
                                            padding: '7 0 0 0',
                                            name: 'wizardFirstMemberType',
                                            boxLabel: 'Personal'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            flex: 1,
                                            padding: '7 0 0 0',
                                            name: 'wizardFirstMemberType',
                                            boxLabel: 'Free'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'wizardFirstFormProfilePreviousButton',
                                            margin: '0 15',
                                            text: 'Previous',
                                            listeners: {
                                                click: {
                                                    fn: 'onWizardFirstFormProfilePreviousButtonClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'wizardFirstFormProfileNextButton',
                                            text: 'Next',
                                            listeners: {
                                                click: {
                                                    fn: 'onWizardFirstFormProfileNextButtonClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'form-panel',
                            bodyPadding: '15 15 15 15',
                            iconAlign: 'top',
                            iconCls: 'fa fa-home',
                            title: 'Address',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            tabConfig: {
                                xtype: 'tab',
                                width: 100
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormPhoneTextField',
                                    fieldLabel: 'Phone',
                                    emptyText: 'Phone number'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormAddressTextField',
                                    fieldLabel: 'Address',
                                    emptyText: 'Address'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormCityTextField',
                                    fieldLabel: 'City',
                                    emptyText: 'City'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'wizardFirstFormPosCodeTextField',
                                    fieldLabel: 'Postcode',
                                    emptyText: 'Poscode'
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'wizardFirstFormAddressPreviousButton',
                                            margin: '0 15',
                                            text: 'Previous',
                                            listeners: {
                                                click: {
                                                    fn: 'onWizardFirstFormAddressPreviousButtonClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'wizardFirstFormAddressNextButton',
                                            text: 'Next',
                                            listeners: {
                                                click: {
                                                    fn: 'onWizardFirstFormAddressNextButtonClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            cls: 'form-panel',
                            bodyPadding: '15 15 15 15',
                            iconAlign: 'top',
                            iconCls: 'fa fa-heart',
                            title: 'Finish',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            tabConfig: {
                                xtype: 'tab',
                                width: 100
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    // flex: 1,
                                    height: 195,
                                    itemId: 'wizardFirstFormFinishBiodataTextarea',
                                    // minHeight: 200,
                                    fieldLabel: 'Bio',
                                    emptyText: 'Tell us your story..'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    hideEmptyLabel: false,
                                    boxLabel: 'Accept the terms and policies'
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'wizardFirstFormFinishTabPreviousButton',
                                            margin: '0 10',
                                            text: 'Previous',
                                            listeners: {
                                                click: {
                                                    fn: 'onWizardFirstFormFinishTabPreviousButtonClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Finish'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row coditas-hidden',
            hidden: true,
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    cls: 'form-panel',
                                    height: 250,
                                    minHeight: 250,
                                    ui: 'widget-panel',
                                    frameHeader: false,
                                    header: false,
                                    title: 'My Panel',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        padding: 15
                                    },
                                    items: [
                                        {
                                            xtype: 'progressbar',
                                            cls: 'form-progress-bar  progressbar-no-text',
                                            height: 10,
                                            itemId: 'formProgressBar',
                                            animate: true
                                        },
                                        {
                                            xtype: 'tabpanel',
                                            flex: 1,
                                            cls: '',
                                            itemId: 'formPanel',
                                            activeTab: 0,
                                            items: [
                                                {
                                                    xtype: 'panel',
                                                    cls: 'form-panel',
                                                    iconCls: 'fa fa-user-plus',
                                                    title: 'Account',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    tabConfig: {
                                                        xtype: 'tab',
                                                        listeners: {
                                                            click: 'onTabClick'
                                                        }
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            itemId: 'wizardFirstFormUsernameTextField',
                                                            fieldLabel: 'Username',
                                                            emptyText: 'Username'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            itemId: 'wizardFirstFormEmailTextField',
                                                            fieldLabel: 'Email address',
                                                            emptyText: 'Email'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    cls: 'form-panel',
                                                    iconCls: 'fa fa-user',
                                                    title: 'Profile',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    tabConfig: {
                                                        xtype: 'tab',
                                                        listeners: {
                                                            click: 'onTabClick1'
                                                        }
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            fieldLabel: 'First name',
                                                            emptyText: 'First name'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            fieldLabel: 'Last name',
                                                            emptyText: 'Last name'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    cls: 'form-panel',
                                                    iconCls: 'fa fa-home',
                                                    title: 'Address',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    tabConfig: {
                                                        xtype: 'tab',
                                                        listeners: {
                                                            click: 'onTabClick2'
                                                        }
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            itemId: 'wizardFirstFormAddressTextField',
                                                            fieldLabel: 'Address',
                                                            emptyText: 'Address'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            itemId: 'wizardFirstFormCityTextField',
                                                            fieldLabel: 'City',
                                                            emptyText: 'City'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    cls: 'form-panel',
                                                    iconCls: 'fa fa-heart',
                                                    title: 'Finish',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    tabConfig: {
                                                        xtype: 'tab',
                                                        listeners: {
                                                            click: 'onTabClick3'
                                                        }
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'stretch'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            itemId: 'formButtons',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbspacer',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'formPreviousButton',
                                                    text: 'Previous',
                                                    listeners: {
                                                        click: {
                                                            fn: 'onPrevButtonClick',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'formNextButton',
                                                    text: 'Next',
                                                    listeners: {
                                                        click: {
                                                            fn: 'onNextButtonClick',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    height: 250,
                                    itemId: 'wizardThirdFormAccountTabPanel',
                                    minHeight: 250,
                                    ui: 'widget-panel',
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            cls: 'form-panel',
                                            iconAlign: 'top',
                                            iconCls: 'fa fa-user-plus',
                                            title: 'Account',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'wizardFirstFormUsernameTextField',
                                                    fieldLabel: 'Username',
                                                    emptyText: 'Username'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'wizardFirstFormEmailTextField',
                                                    fieldLabel: 'Email address',
                                                    emptyText: 'Email'
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormPreviousButton',
                                                            text: 'Previous'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormNextButton',
                                                            text: 'Next'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            cls: 'form-panel',
                                            iconAlign: 'top',
                                            iconCls: 'fa fa-user',
                                            title: 'Profile',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: 'First name',
                                                    emptyText: 'First name'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: 'Last name',
                                                    emptyText: 'Last name'
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormProfilePreviousButton',
                                                            text: 'Previous'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormProfileNextButton',
                                                            text: 'Next'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            cls: 'form-panel',
                                            iconAlign: 'top',
                                            iconCls: 'fa fa-home',
                                            title: 'Address',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'wizardFirstFormCityTextField',
                                                    fieldLabel: 'Phone Number',
                                                    emptyText: 'Phone number'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'wizardFirstFormAddressTextField',
                                                    fieldLabel: 'Address',
                                                    emptyText: 'Address'
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormAddressPreviousButton',
                                                            text: 'Previous'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormAddressNextButton',
                                                            text: 'Next'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            cls: 'form-panel',
                                            iconAlign: 'top',
                                            iconCls: 'fa fa-heart',
                                            title: 'Finish',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    }
                                                },
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'tbspacer',
                                                            flex: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormFinishTabPreviousButton',
                                                            text: 'Previous'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            itemId: 'wizardThirdFormFinishTabFinishButton',
                                                            text: 'Finish'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onTabClick: function(button, e, eOpts) {
        e.stopEvent();
    },

    onTabClick1: function(button, e, eOpts) {
        e.stopEvent();
    },

    onTabClick2: function(button, e, eOpts) {
        e.stopEvent();
    },

    onTabClick3: function(button, e, eOpts) {
        e.stopEvent();
    }

});