/*
 * File: app/view/ui/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.ui.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.uiloginwindow',

    requires: [
        'SenchaDash.view.ui.LoginWindowViewModel',
        'SenchaDash.view.ui.LoginWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    controller: 'uiloginwindow',
    viewModel: {
        type: 'uiloginwindow'
    },
    autoShow: true,
    closable: false,
    title: 'Sencha',
    titleAlign: 'center',
    maximized: true,
    modal: true,

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: 'Sign In To Your Account',
            layout: {
                type: 'vbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    flex: 1,
                    inputType: 'email',
                    allowBlank: false,
                    emptyText: 'example@example.com',
                    vtype: 'email'
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    inputType: 'password',
                    allowBlank: false,
                    emptyText: 'Password'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            boxLabel: 'Remember Me',
                            checked: true
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            glyph: 72,
                            iconAlign: 'right',
                            text: 'Forgot Password',
                            listeners: {
                                click: 'onForgotPasswordButtonClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'button',
                    flex: 1,
                    glyph: 72,
                    iconAlign: 'right',
                    text: 'Login',
                    listeners: {
                        click: 'onLoginButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    glyph: 72,
                    iconAlign: 'right',
                    text: 'Login With Facebook'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    glyph: 72,
                    iconAlign: 'right',
                    text: 'Create New Account',
                    listeners: {
                        click: 'onCreateNewAccountClick'
                    }
                }
            ]
        }
    ]

});