/*
 * File: app/view/ui/MenusContainerViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.ui.MenusContainerViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.uimenuscontainer',

    requires: [
        'Ext.data.Store',
        'Ext.data.field.Field'
    ],

    stores: {
        menuComboboxStore: {
            data: [
                {
                    identifier: 18,
                    textToShow: 'cum'
                },
                {
                    identifier: 775,
                    textToShow: 'eius'
                },
                {
                    identifier: 237,
                    textToShow: 'laudantium'
                },
                {
                    identifier: 472,
                    textToShow: 'et'
                },
                {
                    identifier: 470,
                    textToShow: 'tenetur'
                }
            ],
            fields: [
                {
                    name: 'identifier'
                },
                {
                    name: 'textToShow'
                }
            ]
        }
    }

});