/*
 * File: app/view/ui/ModalsContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.ui.ModalsContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.uimodalscontainer',

    requires: [
        'SenchaDash.view.ui.ModalsContainerViewModel',
        'SenchaDash.view.ui.ModalsContainerViewController',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    controller: 'uimodalscontainer',
    viewModel: {
        type: 'uimodalscontainer'
    },
    cls: 'ui-modal-container',
    width: 400,

    items: [
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'panel',
                            height: 250,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 20,
                            title: 'Animation Modals',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'showSlideDownPopupButton',
                                    margin: 5,
                                    text: 'Vertical',
                                    listeners: {
                                        click: 'onShowSlideDownPopupButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'showDefaultPopupButton',
                                    margin: 5,
                                    text: 'None',
                                    listeners: {
                                        click: 'onShowDefaultPopupButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'anim1PopupButton',
                                    margin: 5,
                                    text: 'Horizontal',
                                    listeners: {
                                        click: 'onAnim1PopupButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'anim2PopupButton',
                                    margin: 5,
                                    text: 'Diagonal',
                                    listeners: {
                                        click: 'onAnim2PopupButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'anim3PopupButton',
                                    margin: 5,
                                    text: 'Path',
                                    listeners: {
                                        click: 'onAnim3PopupButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'panel',
                            height: 250,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 20,
                            title: 'Optional sizes',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    cls: 'large-modal-button',
                                    itemId: 'showWidePopupButton',
                                    margin: 5,
                                    text: 'Large modal',
                                    listeners: {
                                        click: 'onShowWidePopupButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    cls: 'small-modal-button',
                                    itemId: 'showSmallPopupButton',
                                    margin: 5,
                                    text: 'Small modal',
                                    listeners: {
                                        click: 'onShowSmallPopupButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'panel',
                            height: 250,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 20,
                            title: 'Bootbox Modals',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    padding: '40 0 0 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            cls: 'alert-modal-button',
                                            itemId: 'showAlertButton',
                                            margin: 5,
                                            text: 'Alert',
                                            listeners: {
                                                click: 'onShowAlertButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            cls: 'confirm-modal-button',
                                            itemId: 'showConfirmButton',
                                            margin: 5,
                                            text: 'Confirm',
                                            listeners: {
                                                click: 'onShowConfirmButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            cls: 'prompt-modal-button',
                                            itemId: 'showPromptButton',
                                            margin: 5,
                                            text: 'Prompt',
                                            listeners: {
                                                click: 'onShowPromptButtonClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'showMultiLinePrompBoxButton',
                                            margin: 5,
                                            text: 'Multi-line Prompt',
                                            listeners: {
                                                click: 'onShowMultiLinePrompBoxButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'showProgressBarBoxButton',
                                            margin: 5,
                                            text: 'Progress Dialog',
                                            listeners: {
                                                click: 'onShowProgressBarBoxButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'showYNCBoxButton',
                                            margin: 5,
                                            text: 'Yes/No/Cancel Dialog',
                                            listeners: {
                                                click: 'onShowYNCBoxButtonClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'panel',
                            height: 250,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 20,
                            title: 'Bootbox Modals',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'showCustomDialogButton',
                                            margin: 5,
                                            text: 'Custom Dialog',
                                            listeners: {
                                                click: 'onShowCustomDialogButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'showHtmlContentDialogButton',
                                            margin: 5,
                                            text: 'HTML Content Dialog',
                                            listeners: {
                                                click: 'onShowHtmlContentDialogButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'showHtmlFormDialogButton',
                                            margin: 5,
                                            text: 'HTML Form',
                                            listeners: {
                                                click: 'onShowHtmlFormDialogButtonClick'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            hidden: true,
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part'
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'panel',
                            height: 250,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 20,
                            title: 'Optional sizes',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});