/*
 * File: app/view/ui/PanelsContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.ui.PanelsContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.uipanelscontainer',

    requires: [
        'SenchaDash.view.ui.PanelsContainerViewModel',
        'Ext.panel.Tool',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.tab.Bar'
    ],

    viewModel: {
        type: 'uipanelscontainer'
    },
    width: 400,

    items: [
        {
            xtype: 'container',
            cls: 'responsive-page-row panel-top-container',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 0.6,
                    cls: 'panel-width',
                    height: 200,
                    html: 'Basic panel example',
                    ui: 'widget-panel',
                    bodyPadding: 20
                },
                {
                    xtype: 'panel',
                    flex: 0.6,
                    cls: 'panel-width',
                    height: 200,
                    html: 'Lorem ipsum dolor sit amet.',
                    ui: 'widget-panel',
                    bodyPadding: 20,
                    title: 'Panel With Header'
                },
                {
                    xtype: 'panel',
                    flex: 0.6,
                    cls: 'panel-width',
                    height: 200,
                    html: 'Lorem ipsum dolor sit amet.',
                    ui: 'widget-panel',
                    bodyPadding: 20,
                    headerPosition: 'bottom',
                    title: 'Panel With Footer'
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'panel',
                            cls: 'tools-panel',
                            height: 200,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 20,
                            title: 'Panel With Tools',
                            tools: [
                                {
                                    xtype: 'tool',
                                    cls: 'fa fa-refresh',
                                    margin:0
                                },
                                {
                                    xtype: 'tool',
                                    cls: 'fa fa-gear',
                                    margin:0
                                },
                                {
                                    xtype: 'tool',
                                    cls: 'fa fa-wrench',
                                    margin:0
                                },
                                {
                                    xtype: 'tool',
                                    cls: 'fa fa-expand',
                                    margin:0
                                },
                                {
                                    xtype: 'tool',
                                    cls: 'fa fa-question-circle',
                                    margin:'0 -10 0 0'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    cls: 'panel-width',
                                    height: 200,
                                    html: 'Lorem ipsum dolor sit amet.',
                                    ui: 'widget-panel',
                                    width: '50%',
                                    bodyPadding: 20,
                                    headerPosition: 'left',
                                    title: 'Panel With Header Left'
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    cls: 'panel-width',
                                    height: 200,
                                    html: 'Lorem ipsum dolor sit amet.',
                                    ui: 'widget-panel',
                                    width: '50%',
                                    bodyPadding: 20,
                                    headerPosition: 'right',
                                    title: 'Panel With Header Right'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'tabpanel',
                            cls: 'panel-with-tab',
                            height: 250,
                            ui: 'widget-panel',
                            title: 'Right Aligned Tabs',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Active Tab',
                                    items: [
                                        {
                                            xtype: 'container',
                                            html: '<div>dhadha sdsjkhd shi8ewiosadjsa ddjsjsdhfjksdkjsdd </div>',
                                            padding: 20
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Another Tab',
                                    items: [
                                        {
                                            xtype: 'container',
                                            html: '<div>dhadha sdsjkhd shiiosadjsa ddjsjsdhfjksdkjsdd Lrem ipsum dolor sit amet. Lorem ipsum dolor sit amet. \nLorem ipsum dolor sit amet.\nLorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum \ndolor sit amet.\nLorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.\nLorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.</div>',
                                            padding: 20
                                        }
                                    ]
                                }
                            ],
                            tabBar: {
                                xtype: 'tabbar',
                                layout: {
                                    type: 'hbox',
                                    align: 'stretch',
                                    pack: 'end'
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    height: 250,
                    items: [
                        {
                            xtype: 'tabpanel',
                            cls: 'panel-with-tab',
                            height: 250,
                            ui: 'widget-panel',
                            title: 'Left Aligned Tabs',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Active Tab',
                                    items: [
                                        {
                                            xtype: 'container',
                                            html: '<div>dhadha sdsjkhd shiiosadjsa ddjsjsdhfjksdkjsdd Lrem ipsum dolor sit amet. Lorem ipsum dolor sit amet. \nLorem ipsum dolor sit amet.\nLorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsu.</div>',
                                            padding: 20
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Inactive Tab',
                                    items: [
                                        {
                                            xtype: 'container',
                                            html: '<div>dhadha sdsjkhd shiiosadjsa ddjsjsdhfjksdkjsdd Lrem ipsum dolor sit amet. Lorem ipsum dolor sit amet. \nLorem ipsum dolor sit amet.\nLorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum \ndolor sit amet.\nLorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.\nLorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.</div>',
                                            padding: 20
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'panel',
                            height: 250,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 15,
                            collapsed: false,
                            collapsible: true,
                            title: 'Expanded by default'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    height: 250,
                    items: [
                        {
                            xtype: 'panel',
                            height: 250,
                            html: 'Lorem ipsum dolor sit amet.',
                            ui: 'widget-panel',
                            bodyPadding: 20,
                            collapsed: true,
                            collapsible: true,
                            title: 'Collapsed by default',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});