/*
 * File: app/view/ui/ToolbarsContainerViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.ui.ToolbarsContainerViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.uitoolbarscontainer',

    requires: [
        'Ext.data.Store',
        'Ext.data.field.Field'
    ],

    stores: {
        paginationGridStore: {
            pageSize: 5,
            data: [
                {
                    Identifier: 226,
                    name: 'qui'
                },
                {
                    Identifier: 995,
                    name: 'sequi'
                },
                {
                    Identifier: 667,
                    name: 'officiis'
                },
                {
                    Identifier: 271,
                    name: 'numquam'
                },
                {
                    Identifier: 226,
                    name: 'qui'
                },
                {
                    Identifier: 995,
                    name: 'sequi'
                },
                {
                    Identifier: 667,
                    name: 'officiis'
                },
                {
                    Identifier: 271,
                    name: 'numquam'
                }
            ],
            fields: [
                {
                    name: 'Identifier'
                },
                {
                    name: 'name'
                }
            ]
        }
    }

});