/*
 * File: app/view/ui/ToolbarsContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaDash.view.ui.ToolbarsContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.uitoolbarscontainer',

    requires: [
        'SenchaDash.view.ui.ToolbarsContainerViewModel',
        'Ext.form.Label',
        'Ext.button.Button',
        'Ext.menu.CheckItem',
        'Ext.form.field.ComboBox',
        'Ext.menu.DatePicker',
        'Ext.menu.ColorPicker',
        'Ext.toolbar.Paging',
        'Ext.grid.Panel',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'uitoolbarscontainer'
    },

    items: [
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 105,
                                    ui: 'widget-panel',
                                    bodyPadding: 10,
                                    title: 'Basic Toolbar',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            cls: 'toolbar-simple-tab',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    margin: '14 0 14 14',
                                                    width: 60,
                                                    text: 'Item 1'
                                                },
                                                {
                                                    xtype: 'label',
                                                    margin: '14 0 14 14',
                                                    width: 60,
                                                    text: 'Item 2'
                                                },
                                                {
                                                    xtype: 'label',
                                                    margin: '14 0 14 14',
                                                    width: 60,
                                                    text: 'Item 3'
                                                },
                                                {
                                                    xtype: 'label',
                                                    margin: '14 0 14 14',
                                                    width: 60,
                                                    text: 'Item 4'
                                                },
                                                {
                                                    xtype: 'label',
                                                    margin: '14 0 14 14',
                                                    width: 60,
                                                    text: 'Item 5'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 105,
                                    ui: 'widget-panel',
                                    bodyPadding: 10,
                                    title: 'Button Toolbar',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            cls: 'toolbar-simple-tab',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    cls: 'grey-background',
                                                    margin: '15 0 15 14',
                                                    width: 80,
                                                    iconCls: 'fa fa-edit',
                                                    text: 'Edit'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'pink-background',
                                                    margin: '15 0 15 14',
                                                    width: 80,
                                                    iconCls: 'fa  fa-trash',
                                                    text: 'Delete'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'blue-background',
                                                    margin: '15 0 15 14',
                                                    width: 80,
                                                    iconCls: 'fa fa-copy ',
                                                    text: 'Copy'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'nevyblue-background',
                                                    margin: '15 0 15 14',
                                                    width: 80,
                                                    iconCls: 'fa fa-cut',
                                                    text: 'Cut'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'purple-background',
                                                    margin: '15 0 15 14',
                                                    width: 80,
                                                    iconCls: 'fa fa-paste',
                                                    text: 'Paste'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 100,
                                    ui: 'widget-panel',
                                    bodyPadding: 20,
                                    title: 'Icons Only Toolbar',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            cls: 'toolbar-simple-tab',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    cls: 'darkblue-background',
                                                    margin: '15 0 15 15',
                                                    width: 50,
                                                    iconCls: 'fa fa-save'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'grey-background',
                                                    margin: '15 0 15 15',
                                                    width: 50,
                                                    iconCls: 'fa fa-edit'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'pink-background',
                                                    margin: '15 0 15 15',
                                                    width: 50,
                                                    iconCls: 'fa  fa-trash'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'blue-background',
                                                    margin: '15 0 15 15',
                                                    width: 50,
                                                    iconCls: 'fa fa-copy '
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'nevyblue-background',
                                                    margin: '15 0 15 15',
                                                    width: 50,
                                                    iconCls: 'fa fa-cut'
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'purple-background',
                                                    margin: '15 0 15 15',
                                                    width: 50,
                                                    iconCls: 'fa fa-paste'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 100,
                                    ui: 'widget-panel',
                                    bodyPadding: 10,
                                    title: 'Horizontal Dropdown Toolbar',
                                    cls:'horizontal-dropdown-toolbar',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            cls: 'toolbar-simple-tab',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    cls: 'blue-background',
                                                    margin: '15 0 15 15',
                                                    width: 100,
                                                    text: 'MyButton',
                                                    menu: {
                                                        xtype: 'menu',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'white-background',
                                                    margin: '15 0 15 15',
                                                    width: 100,
                                                    text: 'MyButton',
                                                    menu: {
                                                        xtype: 'menu',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'purple-background',
                                                    margin: '15 0 15 15',
                                                    width: 100,
                                                    text: 'MyButton',
                                                    menu: {
                                                        xtype: 'menu',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-cog',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-users',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-user-times',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-mail-reply',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa  fa-trash',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'nevyblue-background',
                                                    margin: '15 0 15 15',
                                                    width: 100,
                                                    text: 'MyButton',
                                                    menu: {
                                                        xtype: 'menu',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'combobox',
                                                                displayField: 'textToShow',
                                                                valueField: 'identifier',
                                                                bind: {
                                                                    store: '{menuComboboxStore}'
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item',
                                                                menu: {
                                                                    xtype: 'datemenu'
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item',
                                                                menu: {
                                                                    xtype: 'colormenu'
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item',
                                                                menu: {
                                                                    xtype: 'menu',
                                                                    width: 120,
                                                                    items: [
                                                                        {
                                                                            xtype: 'menucheckitem',
                                                                            text: 'Menu Item'
                                                                        },
                                                                        {
                                                                            xtype: 'menucheckitem',
                                                                            text: 'Menu Item'
                                                                        },
                                                                        {
                                                                            xtype: 'menucheckitem',
                                                                            text: 'Menu Item'
                                                                        }
                                                                    ]
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item',
                                                                menu: {
                                                                    xtype: 'menu',
                                                                    width: 120,
                                                                    items: [
                                                                        {
                                                                            xtype: 'container',
                                                                            height: 150,
                                                                            width: 150,
                                                                            layout: {
                                                                                type: 'vbox',
                                                                                align: 'stretch'
                                                                            },
                                                                            items: [
                                                                                {
                                                                                    xtype: 'container',
                                                                                    flex: 1,
                                                                                    width: 150,
                                                                                    layout: {
                                                                                        type: 'hbox',
                                                                                        align: 'stretch'
                                                                                    },
                                                                                    items: [
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            iconCls: 'fa fa-users',
                                                                                            text: 'MyButton'
                                                                                        },
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            iconCls: 'fa fa-user-plus',
                                                                                            text: 'MyButton'
                                                                                        }
                                                                                    ]
                                                                                },
                                                                                {
                                                                                    xtype: 'container',
                                                                                    flex: 1,
                                                                                    width: 150,
                                                                                    layout: {
                                                                                        type: 'vbox',
                                                                                        align: 'stretch'
                                                                                    },
                                                                                    items: [
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            text: 'MyButton'
                                                                                        },
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            text: 'MyButton'
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            }
                                                        ]
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'responsive-page-row',
            layout: 'anchor',
            items: [
                {
                    xtype: 'container',
                    cls: 'left-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 370,
                                    ui: 'widget-panel',
                                    bodyPadding: 10,
                                    title: 'Pagination Toolbar',
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            bind: {
                                                store: '{paginationGridStore}'
                                            }
                                        }
                                    ],
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            hideHeaders: true,
                                            bind: {
                                                store: '{paginationGridStore}'
                                            },
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'name',
                                                    text: 'Name',
                                                    flex: 2
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'Identifier',
                                                    text: 'Price',
                                                    flex: 1
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'right-part',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'panel',
                                    height: 370,
                                    ui: 'widget-panel',
                                    bodyPadding: 10,
                                    title: 'Vertical Toolbar',
                                    cls:'vertical-toolbar',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            cls: 'toolbar-simple-tab',
                                            margin: '',
                                            vertical: true,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    cls: 'darkblue-background',
                                                    margin: '15 15 0 15',
                                                    iconCls: 'fa fa-search',
                                                    menu: {
                                                        xtype: 'menu',
                                                        defaultAlign: 'br?',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'grey-background',
                                                    margin: '15 15 0 15',
                                                    iconCls: 'fa fa-star',
                                                    menu: {
                                                        xtype: 'menu',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menucheckitem',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'blue-background',
                                                    margin: '15 15 0 15',
                                                    iconCls: 'fa fa-desktop',
                                                    menu: {
                                                        xtype: 'menu',
                                                        defaultAlign: 'br?',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'pink-background',
                                                    margin: '15 15 0 15',
                                                    iconCls: 'fa fa-cogs',
                                                    menu: {
                                                        xtype: 'menu',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-cog',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-users',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-user-times',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa fa-mail-reply',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                iconCls: 'fa  fa-trash',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'purple-background',
                                                    margin: '15 15 0 15',
                                                    iconCls: 'fa fa-upload',
                                                    menu: {
                                                        xtype: 'menu',
                                                        defaultAlign: 'br?',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Menu Item'
                                                            }
                                                        ]
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    cls: 'nevyblue-background',
                                                    margin: '15 15 0 15',
                                                    iconCls: 'fa  fa-calendar',
                                                    menu: {
                                                        xtype: 'menu',
                                                        width: 120,
                                                        items: [
                                                            {
                                                                xtype: 'combobox',
                                                                hidden: true,
                                                                displayField: 'textToShow',
                                                                valueField: 'identifier',
                                                                bind: {
                                                                    store: '{menuComboboxStore}'
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Date Picker',
                                                                menu: {
                                                                    xtype: 'datemenu'
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Color Picker',
                                                                menu: {
                                                                    xtype: 'colormenu'
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'List Menu',
                                                                menu: {
                                                                    xtype: 'menu',
                                                                    width: 120,
                                                                    items: [
                                                                        {
                                                                            xtype: 'menucheckitem',
                                                                            text: 'Menu Item'
                                                                        },
                                                                        {
                                                                            xtype: 'menucheckitem',
                                                                            text: 'Menu Item'
                                                                        },
                                                                        {
                                                                            xtype: 'menucheckitem',
                                                                            text: 'Menu Item'
                                                                        }
                                                                    ]
                                                                }
                                                            },
                                                            {
                                                                xtype: 'menuitem',
                                                                text: 'Button List',
                                                                menu: {
                                                                    xtype: 'menu',
                                                                    width: 120,
                                                                    items: [
                                                                        {
                                                                            xtype: 'container',
                                                                            cls: 'list-menu-button',
                                                                            height: 150,
                                                                            width: 150,
                                                                            layout: {
                                                                                type: 'vbox',
                                                                                align: 'stretch'
                                                                            },
                                                                            items: [
                                                                                {
                                                                                    xtype: 'container',
                                                                                    flex: 1,
                                                                                    width: 150,
                                                                                    layout: {
                                                                                        type: 'vbox',
                                                                                        align: 'stretch'
                                                                                    },
                                                                                    items: [
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            iconCls: 'fa fa-users',
                                                                                            text: 'Button 1'
                                                                                        },
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            iconCls: 'fa fa-user-plus',
                                                                                            text: 'Button 2'
                                                                                        }
                                                                                    ]
                                                                                },
                                                                                {
                                                                                    xtype: 'container',
                                                                                    flex: 1,
                                                                                    width: 150,
                                                                                    layout: {
                                                                                        type: 'vbox',
                                                                                        align: 'stretch'
                                                                                    },
                                                                                    items: [
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            text: 'Button 3'
                                                                                        },
                                                                                        {
                                                                                            xtype: 'button',
                                                                                            flex: 1,
                                                                                            text: 'Button 4'
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            }
                                                        ]
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});